# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasteryapp', '0002_read_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=256)),
                ('episode', models.CharField(max_length=256)),
                ('location', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='read',
            name='date_created',
            field=models.DateTimeField(default=None, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='read',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasteryapp.Slot'),
        ),
    ]
