# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasteryapp', '0003_auto_20171102_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Date created'),
        ),
    ]
