# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasteryapp', '0004_auto_20171102_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 1, 4, 59, 159184), verbose_name='Date created'),
        ),
    ]
