# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasteryapp', '0005_auto_20171102_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
    ]
