# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasteryapp', '0006_auto_20171102_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('release_date', models.DateTimeField(verbose_name='Release date')),
                ('read_close_date', models.DateTimeField(verbose_name='Date when read copy closes')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('producer', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='slot',
            name='show',
        ),
        migrations.AlterField(
            model_name='slot',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasteryapp.Episode'),
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasteryapp.Show'),
        ),
    ]
